### ISSUE TITLE
stack level too deep (SystemStackError) when loading the gem

### ISSUE THREAD

**Issue by kyranb** [amree/teecket#26]
I'm trying to add some support for additional airlines and when running `ruby -Ilib ./bin/teecket KBR SZB 12-12-2016` I hit some form of recursion:

```
/Users/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:2040:in `initialize_dup': stack level too deep (SystemStackError)
       	from /Users/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:2040:in `dup'
       	from /Users/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:2040:in `block in initialize'
       	from /Users/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:2038:in `each'
       	from /Users/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:2038:in `initialize'
       	from /Users/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/remote_specification.rb:78:in `new'
       	from /Users/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/remote_specification.rb:78:in `method_missing'
       	from /Users/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/rubygems_integration.rb:369:in `block (2 levels) in replace_bin_path'
       	from /Users/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/rubygems_integration.rb:369:in `find'
       	 ... 7067 levels...
       	from /Users/user/Code/teecket/bin/teecket:17:in `load'
       	from /Users/user/Code/teecket/bin/teecket:17:in `<top (required)>'
       	from teecket/bin/teecket:17:in `load'
       	from teecket/bin/teecket:17:in `<main>'
```

**Comment by amree** [comment]
I think I got this error before. I'll dig more into it when I have time
